version: "3.8"
services:
  postgres:
    container_name: postgres_bookStore
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: book
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_bookStore
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5059:80"